import { Employee } from '../../dto/employee/Employee';

export const MOCK_EMPLOYEES: (Employee & { password: string })[] = [
  {
    personId: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@acme.com',
    role: 'Developer',
    birthDate: '08/13/1990',
    employeeNum: 'EMP001',
    employedDate: '08/13/2020',
    employeeStatus: 'Deleted',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane@acme.com',
    role: 'Developer',
    birthDate: '07/10/1992',
    employeeNum: 'EMP002',
    employedDate: '05/12/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 3,
    firstName: 'Alice',
    lastName: 'Brown',
    email: 'alice@acme.com',
    role: 'Manager',
    birthDate: '03/18/1988',
    employeeNum: 'EMP003',
    employedDate: '09/01/2018',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 4,
    firstName: 'Mark',
    lastName: 'Taylor',
    email: 'admin@acme.com',
    role: 'Manager',
    birthDate: '11/23/1985',
    employeeNum: 'EMP004',
    employedDate: '01/15/2015',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'admin123',
  },
  {
    personId: 5,
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma@acme.com',
    role: 'Developer',
    birthDate: '06/25/1995',
    employeeNum: 'EMP005',
    employedDate: '02/20/2022',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 6,
    firstName: 'Liam',
    lastName: 'Johnson',
    email: 'liam@acme.com',
    role: 'Developer',
    birthDate: '09/30/1993',
    employeeNum: 'EMP006',
    employedDate: '08/13/2023',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 7,
    firstName: 'Sophia',
    lastName: 'Martinez',
    email: 'sophia@acme.com',
    role: 'Developer',
    birthDate: '04/14/1994',
    employeeNum: 'EMP007',
    employedDate: '10/05/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 8,
    firstName: 'Daniel',
    lastName: 'Clark',
    email: 'daniel@acme.com',
    role: 'Developer',
    birthDate: '12/02/1991',
    employeeNum: 'EMP008',
    employedDate: '07/19/2020',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 9,
    firstName: 'Olivia',
    lastName: 'Harris',
    email: 'olivia@acme.com',
    role: 'Developer',
    birthDate: '01/17/1996',
    employeeNum: 'EMP009',
    employedDate: '04/10/2022',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 10,
    firstName: 'Noah',
    lastName: 'Evans',
    email: 'noah@acme.com',
    role: 'Developer',
    birthDate: '05/09/1990',
    employeeNum: 'EMP010',
    employedDate: '11/15/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 11,
    firstName: 'Isabella',
    lastName: 'Thomas',
    email: 'isabella@acme.com',
    role: 'Manager',
    birthDate: '02/22/1989',
    employeeNum: 'EMP011',
    employedDate: '08/30/2019',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 12,
    firstName: 'James',
    lastName: 'Wright',
    email: 'james@acme.com',
    role: 'Developer',
    birthDate: '09/04/1992',
    employeeNum: 'EMP012',
    employedDate: '03/05/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 13,
    firstName: 'Mia',
    lastName: 'Bennett',
    email: 'mia@acme.com',
    role: 'Developer',
    birthDate: '11/27/1995',
    employeeNum: 'EMP013',
    employedDate: '06/01/2022',
    employeeStatus: 'Deleted',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 14,
    firstName: 'Ethan',
    lastName: 'Hall',
    email: 'ethan@acme.com',
    role: 'Developer',
    birthDate: '03/16/1994',
    employeeNum: 'EMP014',
    employedDate: '12/12/2020',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 15,
    firstName: 'Ava',
    lastName: 'Lewis',
    email: 'ava@acme.com',
    role: 'Manager',
    birthDate: '07/21/1991',
    employeeNum: 'EMP015',
    employedDate: '09/14/2019',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 16,
    firstName: 'William',
    lastName: 'King',
    email: 'william@acme.com',
    role: 'Developer',
    birthDate: '10/02/1993',
    employeeNum: 'EMP016',
    employedDate: '05/18/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 17,
    firstName: 'Charlotte',
    lastName: 'Scott',
    email: 'charlotte@acme.com',
    role: 'Developer',
    birthDate: '12/13/1992',
    employeeNum: 'EMP017',
    employedDate: '07/22/2020',
    employeeStatus: 'Deleted',
    terminatedDate: '',
    password: 'password123',
  },
  {
    personId: 18,
    firstName: 'Benjamin',
    lastName: 'Adams',
    email: 'benjamin@acme.com',
    role: 'Developer',
    birthDate: '04/29/1990',
    employeeNum: 'EMP018',
    employedDate: '01/10/2021',
    employeeStatus: 'Active',
    terminatedDate: '',
    password: 'password123',
  },
];
